runtime: java11
env: standard
runtime_config:
  jdk: openjdk11
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
  - url: /.*
    script: this field is required, but ignored
entrypoint: java -Xmx64m -jar pubsub-0.0.1-SNAPSHOT.jar

